import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Menu, X, UserPlus, FileText, Search, CreditCard, Download, BookOpen, Bell, CalendarDays, MapPin, Phone, Mail, ExternalLink, CheckCircle2, AlertCircle, Home as HomeIcon } from 'lucide-react';
import './styles.css';
import { quickActions, infoCards, importantDates, notifications, syllabus, centers, faqs } from './data/siteData';

const icons = { UserPlus, FileText, Search, CreditCard, Download, BookOpen };
const nav = [
  ['/', 'Home'], ['/notification', 'Notification'], ['/syllabus', 'Syllabus'], ['/exam-pattern', 'Exam Pattern'], ['/user-guide', 'User Guide'], ['/regional-centers', 'Regional Centers'], ['/important-dates', 'Important Dates'], ['/contact', 'Contact']
];

function go(path){ window.history.pushState({}, '', path); window.dispatchEvent(new Event('popstate')); window.scrollTo(0,0); }
function Link({to, children, className=''}){ return <button className={className} onClick={()=>go(to)}>{children}</button> }
function Header(){ const [open,setOpen]=useState(false); return <>
  <div className="topbar"><span>PGCET 2026 Official Admission Portal</span><span><Phone size={14}/> 040-12345678 &nbsp; <Mail size={14}/> helpdesk@pgcet2026.in</span></div>
  <header className="header"><div className="brand" onClick={()=>go('/')}><div className="logo">PG</div><div><h1>PGCET 2026</h1><p>Post Graduate Common Entrance Test</p></div></div><button className="hamb" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>
  <nav className={`nav ${open?'show':''}`}>{nav.map(([p,n])=><Link key={p} to={p} className={location.pathname===p?'active':''}>{n}</Link>)}</nav>
</> }
function Footer(){return <footer><div className="footer-grid"><div><h3>PGCET 2026</h3><p>Admission portal for postgraduate common entrance test information, applications, hall tickets, syllabus, dates and candidate support.</p></div><div><h4>Quick Links</h4>{quickActions.slice(0,4).map(q=><Link key={q.title} to={q.path}>{q.title}</Link>)}</div><div><h4>Support</h4><Link to="/contact">Helpdesk Contact</Link><Link to="/regional-centers">Regional Centers</Link><Link to="/user-guide">User Guide</Link><Link to="/notification">Notifications</Link></div></div><p className="copy">© 2026 PGCET. Designed for demo/admission portal use.</p></footer>}
function Hero(){return <section className="hero"><div><p className="tag">Admissions Open</p><h2>PGCET 2026</h2><p>Apply for MBA, MCA, M.Tech, M.Pharmacy and other postgraduate professional courses through a clean, fast and mobile-friendly candidate portal.</p><div className="hero-actions"><Link to="/registration" className="primary">Apply Now</Link><Link to="/notification" className="secondary">View Notification</Link></div></div><div className="notice"><Bell/><h3>Latest Update</h3><p>Online application window is open. Candidates should complete registration before the last date to avoid late fee.</p><Link to="/important-dates">Check schedule <ExternalLink size={14}/></Link></div></section>}
function Home(){return <><Hero/><section className="panel"><h2>Quick Actions</h2><div className="cards">{quickActions.map(q=>{const I=icons[q.icon]; return <Link to={q.path} className="card" key={q.title}><I/><b>{q.title}</b><span>{q.desc}</span></Link>})}</div></section><section className="split"><div className="panel"><h2>Information Center</h2><div className="info-grid">{infoCards.map(c=><Link key={c.title} to={c.path} className="info"><CheckCircle2/><b>{c.title}</b><span>{c.desc}</span></Link>)}</div></div><div className="panel side"><h2>Important Dates</h2>{importantDates.slice(0,5).map(d=><p className="date" key={d[0]}><span>{d[0]}</span><b>{d[1]}</b></p>)}<Link to="/important-dates" className="mini">View all dates</Link><h2>Helpline Contact</h2><p><Phone size={16}/> 040-12345678</p><p><Mail size={16}/> helpdesk@pgcet2026.in</p></div></section><Page title="About PGCET 2026"><p>PGCET 2026 is a state-level entrance test for admission into postgraduate professional courses. This portal provides candidate registration, application flow, downloadable resources, exam information, helpdesk contacts and status-check features.</p></Page><FAQ/></>}
function Page({title, children}){return <section className="panel page"><h2>{title}</h2>{children}</section>}
function Notification(){return <Page title="Notification"><p>Download official circulars and latest updates below.</p><div className="list">{notifications.map(n=><a className="row" href={n.file} download key={n.title}><Bell/><span><b>{n.title}</b><small>{n.date} • {n.type}</small></span><Download/></a>)}</div></Page>}
function Syllabus(){return <Page title="Syllabus"><p>Course-wise syllabus links are available here.</p><div className="cards">{syllabus.map(s=><div className="card static" key={s.course}><BookOpen/><b>{s.course}</b><ul>{s.topics.map(t=><li key={t}>{t}</li>)}</ul><a className="primary small" href={s.file} download>Download PDF</a></div>)}</div></Page>}
function ExamPattern(){return <Page title="Exam Pattern"><div className="table-wrap"><table><tbody><tr><th>Mode</th><td>Computer Based Test / Online</td></tr><tr><th>Question Type</th><td>Multiple Choice Questions</td></tr><tr><th>Total Questions</th><td>120</td></tr><tr><th>Total Marks</th><td>120</td></tr><tr><th>Duration</th><td>120 minutes</td></tr><tr><th>Negative Marking</th><td>No negative marking for wrong answers</td></tr></tbody></table></div></Page>}
function UserGuide(){return <Page title="User Guide"><ol className="steps"><li>Open Applicant Registration and create your profile.</li><li>Verify mobile/email details and login to the dashboard.</li><li>Fill personal, academic, course and category details.</li><li>Upload photo, signature and required documents.</li><li>Pay application fee and download acknowledgement.</li><li>Download hall ticket from the portal when released.</li></ol></Page>}
function Regional(){return <Page title="Regional Centers"><div className="table-wrap"><table><thead><tr><th>City</th><th>Center</th><th>Contact</th></tr></thead><tbody>{centers.map(c=><tr key={c[0]}><td>{c[0]}</td><td>{c[1]}</td><td>{c[2]}</td></tr>)}</tbody></table></div></Page>}
function Dates(){return <Page title="Important Dates"><div className="timeline">{importantDates.map(d=><div key={d[0]}><CalendarDays/><span>{d[0]}</span><b>{d[1]}</b></div>)}</div></Page>}
function Contact(){return <Page title="Contact & Support"><div className="contact"><p><Phone/> Helpdesk: 040-12345678 / 040-87654321</p><p><Mail/> Email: helpdesk@pgcet2026.in</p><p><MapPin/> Office: PGCET Convener Office, Hyderabad, Telangana</p></div><FAQ/></Page>}
function FormPage({type}){const [data,setData]=useState({name:'',mobile:'',email:'',reg:''}); const [msg,setMsg]=useState(''); const submit=e=>{e.preventDefault(); setMsg(type==='track'?`Status for ${data.reg||'your application'}: Submitted / Under verification.`:'Details saved successfully. This demo portal stores the form locally for preview.'); localStorage.setItem('pgcet-'+type, JSON.stringify(data));}; return <Page title={type==='track'?'Track Application': type==='payment'?'Payment Status': type==='hall'?'Hall Ticket Download': type==='application'?'Fill Application Form':'Applicant Registration'}><form className="form" onSubmit={submit}>{type!=='registration'&&<input placeholder="Registration Number" value={data.reg} onChange={e=>setData({...data,reg:e.target.value})}/>} {(type==='registration'||type==='application')&&<><input required placeholder="Candidate Name" value={data.name} onChange={e=>setData({...data,name:e.target.value})}/><input required placeholder="Mobile Number" value={data.mobile} onChange={e=>setData({...data,mobile:e.target.value})}/><input required type="email" placeholder="Email ID" value={data.email} onChange={e=>setData({...data,email:e.target.value})}/></>}<button className="primary">Submit</button></form>{msg&&<div className="success"><AlertCircle/>{msg}</div>}</Page>}
function FAQ(){return <section className="panel"><h2>Frequently Asked Questions</h2>{faqs.map(f=><details key={f[0]}><summary>{f[0]}</summary><p>{f[1]}</p></details>)}</section>}
function SearchPage(){const [q,setQ]=useState(''); const all=[...quickActions,...infoCards,...notifications.map(n=>({title:n.title,desc:n.date,path:'/notification'}))]; const res=useMemo(()=>all.filter(x=>(x.title+x.desc).toLowerCase().includes(q.toLowerCase())),[q]); return <Page title="Search Portal"><input className="search" placeholder="Search quick links, notices, syllabus..." value={q} onChange={e=>setQ(e.target.value)}/><div className="list">{res.map(r=><button className="row" onClick={()=>go(r.path||'/')} key={r.title}><Search/><span><b>{r.title}</b><small>{r.desc}</small></span></button>)}</div></Page>}
function App(){const [path,setPath]=useState(location.pathname); React.useEffect(()=>{const f=()=>setPath(location.pathname); addEventListener('popstate',f); return()=>removeEventListener('popstate',f)},[]); let page = path==='/'?<Home/>:path==='/notification'?<Notification/>:path==='/syllabus'?<Syllabus/>:path==='/exam-pattern'?<ExamPattern/>:path==='/user-guide'?<UserGuide/>:path==='/regional-centers'?<Regional/>:path==='/important-dates'?<Dates/>:path==='/contact'?<Contact/>:path==='/registration'?<FormPage type="registration"/>:path==='/application-form'?<FormPage type="application"/>:path==='/track-application'?<FormPage type="track"/>:path==='/payment-status'?<FormPage type="payment"/>:path==='/hall-ticket'?<FormPage type="hall"/>:path==='/search'?<SearchPage/>:<Page title="Page Not Found"><p>This page is not available.</p><Link to="/" className="primary"><HomeIcon size={16}/> Go Home</Link></Page>; return <><Header/><main>{page}</main><Footer/></>}
createRoot(document.getElementById('root')).render(<App/>);
